
dataparallel: 1
workers: 4
model_path : "save"   # set to the directory containing `checkpoint_##.tar`
dataset_dir: "./datasets"
seed: 0
start_epoch: 0
epochs: 50

dataset: "CIFAR100" # STL10
data : "cifar" #imagenet
arch: "resnet18"

strength : 0.5
temperature: 0.5

batch_size: 256
image_size: 32

optimizer: "lars" # or lars (experimental)
warmup: 0.1
weight_decay: 1.0e-04
lr : 1.5
lr_schedule : "warmup-anneal"
lr_scaling : "sqrt"

logistic_batch_size: 512
logistic_epochs: 500
